# Generated by Django 4.1 on 2023-12-06 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clasesmaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreclase', models.CharField(max_length=80, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Clases de maquina',
                'verbose_name_plural': 'Clases de maquinas',
            },
        ),
        migrations.CreateModel(
            name='maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripcion')),
                ('fecham', models.DateField(verbose_name='Ultima mantencion')),
                ('estado', models.CharField(blank=True, choices=[{'Funcionando ', 'Funcionando'}, {'Dañado ', 'Dañado'}], max_length=40, null=True)),
                ('condicionn', models.CharField(blank=True, choices=[{'Libre', 'Libre '}, {'En uso', 'En uso '}], max_length=40, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('clasemaq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.clasesmaquinas')),
            ],
            options={
                'verbose_name': 'Inventario maquina',
                'verbose_name_plural': 'Inventario maquinas',
            },
        ),
        migrations.CreateModel(
            name='consumibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('cantidad', models.PositiveBigIntegerField(verbose_name='Cantidad')),
                ('clas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.clasesmaquinas')),
            ],
            options={
                'verbose_name': 'Inventario consumible',
                'verbose_name_plural': 'Inventario consumibles',
            },
        ),
    ]
