# Generated by Django 4.1 on 2023-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_solicitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquina',
            name='condicionn',
            field=models.CharField(blank=True, choices=[('Libre', 'Libre'), ('En uso', 'En uso')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='estado',
            field=models.CharField(blank=True, choices=[('Funcionando', 'Funcionando'), ('Dañado', 'Dañado')], max_length=40, null=True),
        ),
    ]
